# Generated by Django 5.0.6 on 2025-11-20 20:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('company', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('branding', 'Branding Project'), ('packaging', 'Packaging Design'), ('consultation', 'Consultation')], default='general', max_length=50)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('tagline', models.CharField(help_text='Short catchy description', max_length=300)),
                ('client_name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('branding', 'Branding'), ('packaging', 'Packaging'), ('print', 'Print Design'), ('environmental', 'Environmental Design'), ('identity', 'Identity & Logo'), ('strategy', 'Brand Strategy')], max_length=50)),
                ('services', models.TextField(help_text='Services provided (e.g., Branding, Logo Design)')),
                ('year', models.IntegerField()),
                ('website_url', models.URLField(blank=True, null=True)),
                ('featured_image', models.ImageField(upload_to='portfolio/featured/')),
                ('challenge', models.TextField(help_text='Describe the challenge/problem')),
                ('solution', models.TextField(help_text='Describe your solution')),
                ('results', models.TextField(blank=True, help_text='Results achieved (optional)')),
                ('testimonial', models.TextField(blank=True)),
                ('testimonial_author', models.CharField(blank=True, max_length=200)),
                ('testimonial_position', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
