# Generated by Django 5.0.6 on 2025-12-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(choices=[('', 'Select a service...'), ('brand_strategy', 'Brand Strategy'), ('identity_logo_design', 'Identity & Logo Design'), ('print_fabrication', 'Print & Fabrication'), ('eco_packaging', 'Eco Packaging Design'), ('environmental_design', 'Environmental Design'), ('workshops_consultations', 'Workshops & Consultations'), ('digital_marketing', 'Digital Marketing'), ('sustainable_website', 'Sustainable Website Development'), ('multiple_services', 'Multiple Services'), ('general_inquiry', 'General Inquiry')], default='', max_length=50),
        ),
    ]
