# Generated by Django 6.0.2 on 2026-03-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contactsubmission_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('primary_skill', models.CharField(max_length=100)),
                ('why_join', models.TextField()),
                ('sample_work', models.FileField(blank=True, null=True, upload_to='collective/portfolios/')),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Collective Application',
                'verbose_name_plural': 'Collective Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
