# Generated by Django 6.0.2 on 2026-03-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_collectiveapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(choices=[('', 'Select a service...'), ('impact_brand_system', 'Impact Brand System'), ('brandpaw_saas', 'BrandPaw™ SaaS'), ('environmental_branding', 'Environmental Branding'), ('marketing_collateral', 'Marketing Collateral Design'), ('sustainable_packaging', 'Sustainable Packaging Design'), ('print_fabrication', 'Print & Fabrication'), ('digital_marketing', 'Digital Marketing'), ('website_development', 'Website Development'), ('workshops_consultations', 'Workshops & Consultations'), ('general_inquiry', 'General Inquiry')], default='', max_length=50),
        ),
    ]
