# Generated by Django 6.0.2 on 2026-08-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contactsubmission_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiveapplication',
            name='challenge_video',
            field=models.FileField(default='', upload_to='collective/videos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectiveapplication',
            name='hope_to_build',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectiveapplication',
            name='hunting_for',
            field=models.CharField(choices=[('Creative confidence', 'Creative confidence'), ('My creative identity', 'My creative identity'), ('Better skills', 'Better skills'), ('Community', 'Community'), ('Opportunities', 'Opportunities'), ('Clients / income', 'Clients / income'), ('Mentorship', 'Mentorship'), ('A clearer career direction', 'A clearer career direction'), ('Other', 'Other')], default='Other', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectiveapplication',
            name='hunting_for_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collectiveapplication',
            name='primary_skill_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collectiveapplication',
            name='video_use_consent',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectiveapplication',
            name='portfolio_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collectiveapplication',
            name='primary_skill',
            field=models.CharField(choices=[('Graphic Design', 'Graphic Design'), ('Brand Design / Branding', 'Brand Design / Branding'), ('Content Creation', 'Content Creation'), ('Photography', 'Photography'), ('Videography', 'Videography'), ('Video Editing', 'Video Editing'), ('Motion Design / Animation', 'Motion Design / Animation'), ('Illustration', 'Illustration'), ('Copywriting / Writing', 'Copywriting / Writing'), ('Creative Strategy', 'Creative Strategy'), ('Social Media / Communications', 'Social Media / Communications'), ('UI/UX Design', 'UI/UX Design'), ('Art Direction', 'Art Direction'), ('Other', 'Other')], max_length=100),
        ),
    ]
