# Generated by Django 6.0.2 on 2026-08-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_collectiveapplication_challenge_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiveapplication',
            name='challenge_video',
            field=models.URLField(max_length=500),
        ),
    ]
