# Generated by Django 6.0.2 on 2026-09-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_collectiveapplication_challenge_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectiveapplication',
            old_name='video_use_consent',
            new_name='content_use_consent',
        ),
        migrations.RemoveField(
            model_name='collectiveapplication',
            name='challenge_video',
        ),
        migrations.AddField(
            model_name='collectiveapplication',
            name='challenge_writeup',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
